spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test_id
            client-secret: test_secret
            scope:
              - email
              - profile
  jpa:
    #전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #테이블 생성 후에 data.sql 실행
    defer-datasource-initialization : true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
#JWT 토큰을 만드는 설정
jwt:
  issuer: ajufresh@gmail.com
  secret_key: test_key